### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/arcadia-web#2]
Add Arcadia's logo as favicon

**Comment by Monal5031** [comment]
PNG is available with Joshua, convert it to SVG.

**Comment by aashutoshrathi** [comment]
Why SVG? PNG is fine.
Also, SVGs are not for favicons.😅

**Comment by rossoskull** [comment]
Will do it.

**Comment by rossoskull** [comment]
@Monal5031 Will do it.

**Comment by Monal5031** [comment]
Go ahead @rossoskull

**Comment by rossoskull** [comment]
@Monal5031 Done in PR#9
